language: node_js
cache: yarn
node_js:
- 10.9.0
env:
  matrix:
  - HUGO_VERSION=0.52
install:
- mkdir bin
- export PATH="${TRAVIS_BUILD_DIR}/bin:${PATH}"
- wget -O "hugo_${HUGO_VERSION}.tar.gz" "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz"
- tar xfvz "./hugo_${HUGO_VERSION}.tar.gz" --exclude "*.md" --exclude "LICENSE" -C
  bin
- yarn
- yarn --cwd functions
- yarn global add firebase-tools
script:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
- NODE_ENV=production yarn build:full
- if [ "$BRANCH" == "master" ]; then export PROJECT=$FIREBASE_PROJECT; else export PROJECT=$FIREBASE_PROJECT_STAGING; fi
- echo $PROJECT
- firebase use $PROJECT --token $FIREBASE_TOKEN
- export COMMIT_HASH=$(echo $TRAVIS_COMMIT | cut -b -6)
- firebase deploy -m "build $TRAVIS_BUILD_NUMBER $BRANCH/$COMMIT_HASH" --non-interactive --token $FIREBASE_TOKEN --except functions
after_success:
- curl "http://www.google.com/ping?sitemap=https://devinschulz.com/sitemap.xml"
