baseURL = "https://devinschulz.com"
languageCode = "en-us"
title = "Devin Schulz"
description = "Articles about React, JavaScript, testing, best practices, performance, and everything else related to front-end development."
theme = "dev"
titleCaseStyle = "AP"
pygmentsUseClasses = true

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
posts = ":title"

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = false
angledQuotes = false

[params]
timeFormatRFC3339 = "2006-01-02T15:04:05Z07:00"
timeFormatDefault = "January 2, 2006"

[params.author]
twitterHandle = "devinschulz_"
