baseURL = "https://devinschulz.com"
languageCode = "en-us"
title = "Devin Schulz"
description = "Articles about React, JavaScript, testing, best practices, performance, and everything else related to front-end development."
titleCaseStyle = "AP"
pygmentsUseClasses = true
disableKinds = ["section"]

[taxonomies]
tag = "tags"

[permalinks]
posts = ":title"

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = false
angledQuotes = false

[params]
timeFormatRFC3339 = "2006-01-02T15:04:05Z07:00"
timeFormatDefault = "January 2, 2006"

[author]
name = "Devin Schulz"     
homepage = "https://devinschulz.com"

[params.author]
twitterHandle = "devinschulz_"

[menu]
  [[menu.main]]
  name = "All topics"
  weight = 1
  url = "/tags"

  [[menu.main]]
  name = "About Me"
  weight = 0
  url = "/about"

[module]
  [[module.mounts]]
  source = "./node_modules/instant.page/instantpage.js"
  target = "assets/js/instantpage.js"