baseURL = "https://devinschulz.com/"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en"
metaDataFormat = "toml"
preserveTaxonomyNames = true
title = "Devin Schulz"
summaryLength = 20
enableGitInfo = true
disqusShortname = "devinschulz"

pygmentsCodeFences = true
pygmentsUseClasses = true

[author]
  name = "Devin Schulz"
  twitter = "devinschulz_"

[params]
  description = "The description"
  brandColor = "#3455db"
  logo = "images/logo.jpg"
  sentryDSN = "https://6be3214d8335461caeb4c6e4ef667158@sentry.io/300767"
  dateFormat = "January 2, 2006"
  githubRepo = "https://github.com/devinschulz/blog"
  commentsEnabled = true

[params.staticman]
  endpoint = "https://api.staticman.net/v2/entry/"
  username = "devinschulz"
  repository = "blog"
  branch = "master"

[params.recaptcha]
  siteKey = "6LcrGVsUAAAAAP2LKjw2P_y_FW1LVE86RZqcfjfg"
  secret = "zV5kYaBUfaIuBGGdSJIEtp8F+6VqWdBcCxUqhI69R4KvfNOw1yTQEGponVJ5uW/VDlSr6UuRmwtCga3+7UwLFnBoh+5Ssl5jlPo7/G6PkFyckd37cCaYtyfXatcIUTSou6O7mBa8DsQnjB569J9tw1VUncGJYPDZEOypGBJ3Ttc="

[[menu.footer]]
  name = "Posts"
  identifier = "posts"
  url = "/posts/"
  weight = 10

[[menu.footer]]
  name = "Sitemap"
  identifier = "sitemap"
  url = "/sitemap.xml"
  weight = 60

[[menu.footer]]
  name = "RSS"
  identifier = "rss"
  url = "/posts/index.xml"
  weight = 70

[[menu.social]]
  name = "Github"
  url = "https://github.com/devinschulz"
  weight = 10
[[menu.social]]
  name = "Twitter"
  url = "https://twitter.com/devinschulz_"
  weight = 20
[[menu.social]]
  name = "Dribbble"
  url = "https://dribbble.com/idev"
  weight = 30
[[menu.social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/devinschulz"
  weight = 40
[[menu.social]]
  name = "Keybase"
  url = "https://keybase.io/devinschulz"
  weight = 50

[taxonomies]
  category = "categories"
