baseURL = "https://devinschulz.com"
languageCode = "en-us"
title = "Devin Schulz"
description = "Articles about React, JavaScript, testing, best practices, performance, and everything else related to front-end development."
titleCaseStyle = "AP"
pygmentsUseClasses = true
enableGitInfo = true

[taxonomies]
tag = "tags"

[permalinks]
posts = ":title"

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = false
angledQuotes = false

[params]
timeFormatRFC3339 = "2006-01-02T15:04:05Z07:00"
timeFormatDefault = "January 2, 2006"

[author]
name = "Devin Schulz"     
homepage = "https://devinschulz.com"

[params.author]
twitterHandle = "devinschulz_"

[menu]
  [[menu.main]]
  name = "All Tags"
  weight = 0
  url = "/tags"

  [[menu.main]]
  name = "About Me"
  weight = 1
  url = "/about"

  [[menu.footer]]
  name = "Privacy"
  weight = 1
  url = "/privacy"

  [[menu.footer]]
  name = "RSS"
  weight = 0
  url = "/posts/index.xml"


[related]
threshold = 80
includeNewer = true
toLower = true

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "keywords"
  weight = 80

