baseURL = "http://example.org/"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en"
metaDataFormat = "toml"
preserveTaxonomyNames = true
sectionPagesMenu = "main"
title = "Devin Schulz"

[params]
  description = "The description"
  author = "Devin Schulz"

[[menu.main]]
  name = "Posts"
  identifier = "posts"
  url = "/posts/"
  weight = 20

[taxonomies]
  category = "categories"
