[build]
  publish = "public"
  command = "yarn build:full"

[build.environment]
  HUGO_VERSION = "0.47.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_ENV = "production"
  # Allow dev dependencies to install when NODE_ENV is set to production
  YARN_FLAGS = "--production=false"
