[build]
  publish = "public"
  command = "gulp netlify && hugo -D && gulp post-process"

[context.production.environment]
  HUGO_VERSION = "0.37.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_ENV = "production"
  # Allow dev dependencies to install when NODE_ENV is set to production
  YARN_FLAGS = "--production=false"
