[build.environment]
  HUGO_VERSION = "0.54.0"
  NPM_VERSION = "6.9.0"

[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "npm run build:preview"
