[build]
command = "npm run build"
publish = "public"

[build.environment]
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm run build:preview"

[context.deploy-preview.environment]
HUGO_ENV = "preview"

[[plugins]]
id = "terser"
package = "./plugins/terser/terser.js"

[plugins.config]
src = "/public/js"

# debugMode = true
[plugins.config.options]
toplevel = true
