[build]
  command = "NODE_ENV=production hugo --gc --minify && npm run minify-js"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.64.1"
  NPM_VERSION = "6.13.7"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "NODE_ENV=production hugo --gc --minify --buildFuture && npm run minify-js"

[context.deploy-preview.environment]
  HUGO_ENV = "preview"

[[redirects]]
  from = "/categories"
  to = "/tags"
  status = 301
  force = true

[[redirects]]
  from = "/categories/*"
  to = "/tags/:splat"
  status = 301

[[redirects]]
  from = "/posts"
  to = "/"
  status = 301
