[build]
  command = "hugo --gc --minify"  
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.64.1"
  NPM_VERSION = "6.13.7"
  NODE_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture"

[context.deploy-preview.environment]
  HUGO_ENV = "preview"
