baseurl: /
languageCode: en
title: Devin Schulz
titleCaseStyle: AP
baseURL: https://devinschulz.com

pygmentsCodeFences: true
pygmentsOptions: 'linenos=1'
pygmentsUseClasses: true
pygmentsUseClassic: false

social:
  twitter: devinschulz_
  github: devinschulz
  linkedin: devinschulz

params:
  author: Devin Schulz
  github: https://github.com/devinschulz
  twitter: https://twitter.com/devinschulz_
  linkedin: https://www.linkedin.com/in/devinschulz
  description: >-
    Articles about React, JavaScript, testing, best practices, performance, and
    everything else related to front-end development.
  socialShareEmail: true
  socialShareFacebook: true
  socialShareLinkedin: true
  socialShareReddit: true
  socialShareTwitter: true

enableRobotsTxt: true
enableGitInfo: true

blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: false
  angledQuotes: false
  latexDashes: true

related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
    - name: keywords
      weight: 20
    - name: tags
      weight: 100
    - name: categories
      weight: 80

permalinks:
  posts: :title

menus:
  main:
    - identifier: projects
      name: Projects
      url: /projects/

